### ISSUE TITLE
contact_picker isn't working

### ISSUE THREAD

**Issue by EphronKarthick** [goderbauer/contact_picker#6]
Hi,

When i pick the contact using contact_picker, its just redirect to back page instead of showing the contact information for particular selected contact.

Thanks,
Karthick

**Comment by goderbauer** [comment]
You need to provide more context (ideally with code snippets and screenshots). How are you using contact_picker? What are you doing that exposes the problem? What was the expected outcome of your action? What did actually happen?

**Comment by EphronKarthick** [comment]
Hi,

Thanks for your response.

I have used contact_picker to select particular contact in the contact list.

Below i have mentioned the screenshot of my flutter app and also pointed
out the expected outcome.

Link : https://www.screencast.com/t/ZYZrLOxSDbC

https://www.screencast.com/t/vrcOBrfkhEg2

Thanks,

Karthick

**Comment by goderbauer** [comment]
What does your code look like where you call the contact_picker?

**Comment by EphronKarthick** [comment]
Hi,

Thanks for your response.

Below i have mentioned the screenshot of code.

Link : https://www.screencast.com/t/mzMzimjmRu4

Please guide me how to fix the issue.

Thanks,
Karthick

**Comment by goderbauer** [comment]
You're not displaying the contact anywhere in your app. If you replace the line `body: new Container()` with something like the following you'll see the selected contact:

```dart
body: new Center(
  child: new Text(_contact == null ? 'No contact selected.' : _contact.toString()),
),
```

**Comment by EphronKarthick** [comment]
Hi,

Thanks for your response. Its working fine.

Thanks,
Karthick
